// Code generated by protoc-gen-go.
// source: formic_api.proto
// DO NOT EDIT!

/*
Package newproto is a generated protocol buffer package.

It is generated from these files:
	formic_api.proto

It has these top-level messages:
	GetAttrRequest
	GetAttrResponse
	Attr
	ReadRequest
	ReadResponse
	SetAttrRequest
	SetAttrResponse
	WriteRequest
	WriteResponse
*/
package newproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetAttrRequest struct {
	Rpcid uint32 `protobuf:"varint,1,opt,name=rpcid" json:"rpcid,omitempty"`
	Inode uint64 `protobuf:"varint,2,opt,name=inode" json:"inode,omitempty"`
}

func (m *GetAttrRequest) Reset()                    { *m = GetAttrRequest{} }
func (m *GetAttrRequest) String() string            { return proto.CompactTextString(m) }
func (*GetAttrRequest) ProtoMessage()               {}
func (*GetAttrRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetAttrRequest) GetRpcid() uint32 {
	if m != nil {
		return m.Rpcid
	}
	return 0
}

func (m *GetAttrRequest) GetInode() uint64 {
	if m != nil {
		return m.Inode
	}
	return 0
}

type GetAttrResponse struct {
	Rpcid uint32 `protobuf:"varint,1,opt,name=rpcid" json:"rpcid,omitempty"`
	Attr  *Attr  `protobuf:"bytes,2,opt,name=attr" json:"attr,omitempty"`
	Err   string `protobuf:"bytes,3,opt,name=err" json:"err,omitempty"`
}

func (m *GetAttrResponse) Reset()                    { *m = GetAttrResponse{} }
func (m *GetAttrResponse) String() string            { return proto.CompactTextString(m) }
func (*GetAttrResponse) ProtoMessage()               {}
func (*GetAttrResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetAttrResponse) GetRpcid() uint32 {
	if m != nil {
		return m.Rpcid
	}
	return 0
}

func (m *GetAttrResponse) GetAttr() *Attr {
	if m != nil {
		return m.Attr
	}
	return nil
}

func (m *GetAttrResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type Attr struct {
	Inode  uint64 `protobuf:"varint,1,opt,name=inode" json:"inode,omitempty"`
	Atime  int64  `protobuf:"varint,2,opt,name=atime" json:"atime,omitempty"`
	Mtime  int64  `protobuf:"varint,3,opt,name=mtime" json:"mtime,omitempty"`
	Ctime  int64  `protobuf:"varint,4,opt,name=ctime" json:"ctime,omitempty"`
	Crtime int64  `protobuf:"varint,5,opt,name=crtime" json:"crtime,omitempty"`
	Mode   uint32 `protobuf:"varint,6,opt,name=mode" json:"mode,omitempty"`
	Valid  int32  `protobuf:"varint,7,opt,name=valid" json:"valid,omitempty"`
	Size   uint64 `protobuf:"varint,8,opt,name=size" json:"size,omitempty"`
	Uid    uint32 `protobuf:"varint,9,opt,name=uid" json:"uid,omitempty"`
	Gid    uint32 `protobuf:"varint,10,opt,name=gid" json:"gid,omitempty"`
}

func (m *Attr) Reset()                    { *m = Attr{} }
func (m *Attr) String() string            { return proto.CompactTextString(m) }
func (*Attr) ProtoMessage()               {}
func (*Attr) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Attr) GetInode() uint64 {
	if m != nil {
		return m.Inode
	}
	return 0
}

func (m *Attr) GetAtime() int64 {
	if m != nil {
		return m.Atime
	}
	return 0
}

func (m *Attr) GetMtime() int64 {
	if m != nil {
		return m.Mtime
	}
	return 0
}

func (m *Attr) GetCtime() int64 {
	if m != nil {
		return m.Ctime
	}
	return 0
}

func (m *Attr) GetCrtime() int64 {
	if m != nil {
		return m.Crtime
	}
	return 0
}

func (m *Attr) GetMode() uint32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

func (m *Attr) GetValid() int32 {
	if m != nil {
		return m.Valid
	}
	return 0
}

func (m *Attr) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Attr) GetUid() uint32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *Attr) GetGid() uint32 {
	if m != nil {
		return m.Gid
	}
	return 0
}

type ReadRequest struct {
	Rpcid  uint32 `protobuf:"varint,1,opt,name=rpcid" json:"rpcid,omitempty"`
	Inode  uint64 `protobuf:"varint,2,opt,name=inode" json:"inode,omitempty"`
	Offset int64  `protobuf:"varint,3,opt,name=offset" json:"offset,omitempty"`
	Size   int64  `protobuf:"varint,4,opt,name=size" json:"size,omitempty"`
}

func (m *ReadRequest) Reset()                    { *m = ReadRequest{} }
func (m *ReadRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()               {}
func (*ReadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReadRequest) GetRpcid() uint32 {
	if m != nil {
		return m.Rpcid
	}
	return 0
}

func (m *ReadRequest) GetInode() uint64 {
	if m != nil {
		return m.Inode
	}
	return 0
}

func (m *ReadRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ReadRequest) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type ReadResponse struct {
	Rpcid   uint32 `protobuf:"varint,1,opt,name=rpcid" json:"rpcid,omitempty"`
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Err     string `protobuf:"bytes,3,opt,name=err" json:"err,omitempty"`
}

func (m *ReadResponse) Reset()                    { *m = ReadResponse{} }
func (m *ReadResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()               {}
func (*ReadResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ReadResponse) GetRpcid() uint32 {
	if m != nil {
		return m.Rpcid
	}
	return 0
}

func (m *ReadResponse) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *ReadResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type SetAttrRequest struct {
	Rpcid uint32 `protobuf:"varint,1,opt,name=rpcid" json:"rpcid,omitempty"`
	Attr  *Attr  `protobuf:"bytes,2,opt,name=attr" json:"attr,omitempty"`
	Valid uint32 `protobuf:"varint,3,opt,name=valid" json:"valid,omitempty"`
}

func (m *SetAttrRequest) Reset()                    { *m = SetAttrRequest{} }
func (m *SetAttrRequest) String() string            { return proto.CompactTextString(m) }
func (*SetAttrRequest) ProtoMessage()               {}
func (*SetAttrRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *SetAttrRequest) GetRpcid() uint32 {
	if m != nil {
		return m.Rpcid
	}
	return 0
}

func (m *SetAttrRequest) GetAttr() *Attr {
	if m != nil {
		return m.Attr
	}
	return nil
}

func (m *SetAttrRequest) GetValid() uint32 {
	if m != nil {
		return m.Valid
	}
	return 0
}

type SetAttrResponse struct {
	Rpcid uint32 `protobuf:"varint,1,opt,name=rpcid" json:"rpcid,omitempty"`
	Attr  *Attr  `protobuf:"bytes,2,opt,name=attr" json:"attr,omitempty"`
	Err   string `protobuf:"bytes,3,opt,name=err" json:"err,omitempty"`
}

func (m *SetAttrResponse) Reset()                    { *m = SetAttrResponse{} }
func (m *SetAttrResponse) String() string            { return proto.CompactTextString(m) }
func (*SetAttrResponse) ProtoMessage()               {}
func (*SetAttrResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *SetAttrResponse) GetRpcid() uint32 {
	if m != nil {
		return m.Rpcid
	}
	return 0
}

func (m *SetAttrResponse) GetAttr() *Attr {
	if m != nil {
		return m.Attr
	}
	return nil
}

func (m *SetAttrResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type WriteRequest struct {
	Rpcid   uint32 `protobuf:"varint,1,opt,name=rpcid" json:"rpcid,omitempty"`
	Inode   uint64 `protobuf:"varint,2,opt,name=inode" json:"inode,omitempty"`
	Offset  int64  `protobuf:"varint,3,opt,name=offset" json:"offset,omitempty"`
	Payload []byte `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *WriteRequest) Reset()                    { *m = WriteRequest{} }
func (m *WriteRequest) String() string            { return proto.CompactTextString(m) }
func (*WriteRequest) ProtoMessage()               {}
func (*WriteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *WriteRequest) GetRpcid() uint32 {
	if m != nil {
		return m.Rpcid
	}
	return 0
}

func (m *WriteRequest) GetInode() uint64 {
	if m != nil {
		return m.Inode
	}
	return 0
}

func (m *WriteRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *WriteRequest) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type WriteResponse struct {
	Rpcid uint32 `protobuf:"varint,1,opt,name=rpcid" json:"rpcid,omitempty"`
	Err   string `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
}

func (m *WriteResponse) Reset()                    { *m = WriteResponse{} }
func (m *WriteResponse) String() string            { return proto.CompactTextString(m) }
func (*WriteResponse) ProtoMessage()               {}
func (*WriteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *WriteResponse) GetRpcid() uint32 {
	if m != nil {
		return m.Rpcid
	}
	return 0
}

func (m *WriteResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*GetAttrRequest)(nil), "newproto.GetAttrRequest")
	proto.RegisterType((*GetAttrResponse)(nil), "newproto.GetAttrResponse")
	proto.RegisterType((*Attr)(nil), "newproto.Attr")
	proto.RegisterType((*ReadRequest)(nil), "newproto.ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "newproto.ReadResponse")
	proto.RegisterType((*SetAttrRequest)(nil), "newproto.SetAttrRequest")
	proto.RegisterType((*SetAttrResponse)(nil), "newproto.SetAttrResponse")
	proto.RegisterType((*WriteRequest)(nil), "newproto.WriteRequest")
	proto.RegisterType((*WriteResponse)(nil), "newproto.WriteResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Formic service

type FormicClient interface {
	GetAttr(ctx context.Context, opts ...grpc.CallOption) (Formic_GetAttrClient, error)
	Read(ctx context.Context, opts ...grpc.CallOption) (Formic_ReadClient, error)
	SetAttr(ctx context.Context, opts ...grpc.CallOption) (Formic_SetAttrClient, error)
	Write(ctx context.Context, opts ...grpc.CallOption) (Formic_WriteClient, error)
}

type formicClient struct {
	cc *grpc.ClientConn
}

func NewFormicClient(cc *grpc.ClientConn) FormicClient {
	return &formicClient{cc}
}

func (c *formicClient) GetAttr(ctx context.Context, opts ...grpc.CallOption) (Formic_GetAttrClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Formic_serviceDesc.Streams[0], c.cc, "/newproto.Formic/GetAttr", opts...)
	if err != nil {
		return nil, err
	}
	x := &formicGetAttrClient{stream}
	return x, nil
}

type Formic_GetAttrClient interface {
	Send(*GetAttrRequest) error
	Recv() (*GetAttrResponse, error)
	grpc.ClientStream
}

type formicGetAttrClient struct {
	grpc.ClientStream
}

func (x *formicGetAttrClient) Send(m *GetAttrRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *formicGetAttrClient) Recv() (*GetAttrResponse, error) {
	m := new(GetAttrResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *formicClient) Read(ctx context.Context, opts ...grpc.CallOption) (Formic_ReadClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Formic_serviceDesc.Streams[1], c.cc, "/newproto.Formic/Read", opts...)
	if err != nil {
		return nil, err
	}
	x := &formicReadClient{stream}
	return x, nil
}

type Formic_ReadClient interface {
	Send(*ReadRequest) error
	Recv() (*ReadResponse, error)
	grpc.ClientStream
}

type formicReadClient struct {
	grpc.ClientStream
}

func (x *formicReadClient) Send(m *ReadRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *formicReadClient) Recv() (*ReadResponse, error) {
	m := new(ReadResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *formicClient) SetAttr(ctx context.Context, opts ...grpc.CallOption) (Formic_SetAttrClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Formic_serviceDesc.Streams[2], c.cc, "/newproto.Formic/SetAttr", opts...)
	if err != nil {
		return nil, err
	}
	x := &formicSetAttrClient{stream}
	return x, nil
}

type Formic_SetAttrClient interface {
	Send(*SetAttrRequest) error
	Recv() (*SetAttrResponse, error)
	grpc.ClientStream
}

type formicSetAttrClient struct {
	grpc.ClientStream
}

func (x *formicSetAttrClient) Send(m *SetAttrRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *formicSetAttrClient) Recv() (*SetAttrResponse, error) {
	m := new(SetAttrResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *formicClient) Write(ctx context.Context, opts ...grpc.CallOption) (Formic_WriteClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Formic_serviceDesc.Streams[3], c.cc, "/newproto.Formic/Write", opts...)
	if err != nil {
		return nil, err
	}
	x := &formicWriteClient{stream}
	return x, nil
}

type Formic_WriteClient interface {
	Send(*WriteRequest) error
	Recv() (*WriteResponse, error)
	grpc.ClientStream
}

type formicWriteClient struct {
	grpc.ClientStream
}

func (x *formicWriteClient) Send(m *WriteRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *formicWriteClient) Recv() (*WriteResponse, error) {
	m := new(WriteResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Formic service

type FormicServer interface {
	GetAttr(Formic_GetAttrServer) error
	Read(Formic_ReadServer) error
	SetAttr(Formic_SetAttrServer) error
	Write(Formic_WriteServer) error
}

func RegisterFormicServer(s *grpc.Server, srv FormicServer) {
	s.RegisterService(&_Formic_serviceDesc, srv)
}

func _Formic_GetAttr_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FormicServer).GetAttr(&formicGetAttrServer{stream})
}

type Formic_GetAttrServer interface {
	Send(*GetAttrResponse) error
	Recv() (*GetAttrRequest, error)
	grpc.ServerStream
}

type formicGetAttrServer struct {
	grpc.ServerStream
}

func (x *formicGetAttrServer) Send(m *GetAttrResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *formicGetAttrServer) Recv() (*GetAttrRequest, error) {
	m := new(GetAttrRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Formic_Read_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FormicServer).Read(&formicReadServer{stream})
}

type Formic_ReadServer interface {
	Send(*ReadResponse) error
	Recv() (*ReadRequest, error)
	grpc.ServerStream
}

type formicReadServer struct {
	grpc.ServerStream
}

func (x *formicReadServer) Send(m *ReadResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *formicReadServer) Recv() (*ReadRequest, error) {
	m := new(ReadRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Formic_SetAttr_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FormicServer).SetAttr(&formicSetAttrServer{stream})
}

type Formic_SetAttrServer interface {
	Send(*SetAttrResponse) error
	Recv() (*SetAttrRequest, error)
	grpc.ServerStream
}

type formicSetAttrServer struct {
	grpc.ServerStream
}

func (x *formicSetAttrServer) Send(m *SetAttrResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *formicSetAttrServer) Recv() (*SetAttrRequest, error) {
	m := new(SetAttrRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Formic_Write_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FormicServer).Write(&formicWriteServer{stream})
}

type Formic_WriteServer interface {
	Send(*WriteResponse) error
	Recv() (*WriteRequest, error)
	grpc.ServerStream
}

type formicWriteServer struct {
	grpc.ServerStream
}

func (x *formicWriteServer) Send(m *WriteResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *formicWriteServer) Recv() (*WriteRequest, error) {
	m := new(WriteRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Formic_serviceDesc = grpc.ServiceDesc{
	ServiceName: "newproto.Formic",
	HandlerType: (*FormicServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAttr",
			Handler:       _Formic_GetAttr_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Read",
			Handler:       _Formic_Read_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "SetAttr",
			Handler:       _Formic_SetAttr_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Write",
			Handler:       _Formic_Write_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "formic_api.proto",
}

func init() { proto.RegisterFile("formic_api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 439 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x53, 0x4d, 0x8f, 0xd3, 0x30,
	0x10, 0xc5, 0xcd, 0xd7, 0xee, 0x6c, 0xb7, 0xac, 0x2c, 0x58, 0x4c, 0x4f, 0x91, 0x4f, 0x39, 0x55,
	0x68, 0x39, 0x70, 0x00, 0x21, 0x21, 0xad, 0xe0, 0x8a, 0x9c, 0x03, 0x27, 0x04, 0x21, 0x76, 0x57,
	0x96, 0x9a, 0x26, 0x38, 0x2e, 0x08, 0xfe, 0x05, 0xff, 0x8e, 0x9f, 0x83, 0x3c, 0x4e, 0xd3, 0x94,
	0x7e, 0xa8, 0x42, 0xec, 0x6d, 0xde, 0x8b, 0x5f, 0xde, 0x9b, 0xf1, 0x18, 0xae, 0xe6, 0xb5, 0xa9,
	0x74, 0xf9, 0xa9, 0x68, 0xf4, 0xac, 0x31, 0xb5, 0xad, 0xe9, 0xd9, 0x52, 0x7d, 0xc7, 0x8a, 0xbf,
	0x82, 0xc9, 0x3b, 0x65, 0xdf, 0x58, 0x6b, 0x84, 0xfa, 0xba, 0x52, 0xad, 0xa5, 0x8f, 0x20, 0x32,
	0x4d, 0xa9, 0x25, 0x23, 0x29, 0xc9, 0x2e, 0x85, 0x07, 0x8e, 0xd5, 0xcb, 0x5a, 0x2a, 0x36, 0x4a,
	0x49, 0x16, 0x0a, 0x0f, 0xf8, 0x47, 0x78, 0xd8, 0xab, 0xdb, 0xa6, 0x5e, 0xb6, 0xea, 0x80, 0x9c,
	0x43, 0x58, 0x58, 0x6b, 0x50, 0x7d, 0x71, 0x33, 0x99, 0xad, 0xfd, 0x67, 0xa8, 0xc5, 0x6f, 0xf4,
	0x0a, 0x02, 0x65, 0x0c, 0x0b, 0x52, 0x92, 0x9d, 0x0b, 0x57, 0xf2, 0xdf, 0x04, 0x42, 0x77, 0x60,
	0xe3, 0x4e, 0x06, 0xee, 0x8e, 0x2d, 0xac, 0xae, 0x7c, 0xa6, 0x40, 0x78, 0xe0, 0xd8, 0x0a, 0xd9,
	0xc0, 0xb3, 0xd5, 0x9a, 0x2d, 0x91, 0x0d, 0x3d, 0x8b, 0x80, 0x5e, 0x43, 0x5c, 0x1a, 0xa4, 0x23,
	0xa4, 0x3b, 0x44, 0x29, 0x84, 0x95, 0xb3, 0x8b, 0xb1, 0x07, 0xac, 0xdd, 0x1f, 0xbe, 0x15, 0x0b,
	0x2d, 0x59, 0x92, 0x92, 0x2c, 0x12, 0x1e, 0xb8, 0x93, 0xad, 0xfe, 0xa9, 0xd8, 0x19, 0x06, 0xc3,
	0xda, 0x35, 0xb2, 0xd2, 0x92, 0x9d, 0xa3, 0xd8, 0x95, 0x8e, 0xb9, 0xd3, 0x92, 0x81, 0x67, 0xee,
	0xb4, 0xe4, 0x0a, 0x2e, 0x84, 0x2a, 0xe4, 0x3f, 0x0c, 0xdd, 0x85, 0xae, 0xe7, 0xf3, 0x56, 0xd9,
	0xae, 0xc3, 0x0e, 0xf5, 0x51, 0x7c, 0x87, 0x58, 0xf3, 0xf7, 0x30, 0xf6, 0x36, 0x47, 0x6f, 0x87,
	0x41, 0xd2, 0x14, 0x3f, 0x16, 0x75, 0x21, 0xd1, 0x69, 0x2c, 0xd6, 0x70, 0xcf, 0x9d, 0x7c, 0x86,
	0x49, 0x7e, 0xca, 0xc2, 0x9c, 0x72, 0xe3, 0xfd, 0x48, 0x03, 0xaf, 0x44, 0xe0, 0x96, 0x2a, 0xbf,
	0xc7, 0xa5, 0x5a, 0xc0, 0xf8, 0x83, 0xd1, 0x56, 0xfd, 0xcf, 0xd1, 0x0f, 0x06, 0x18, 0x6e, 0x0d,
	0x90, 0xbf, 0x80, 0xcb, 0xce, 0xed, 0x68, 0x2b, 0x5d, 0xcc, 0x51, 0x1f, 0xf3, 0xe6, 0xd7, 0x08,
	0xe2, 0xb7, 0xf8, 0x6e, 0xe9, 0x2d, 0x24, 0xdd, 0x2b, 0xa3, 0x6c, 0xd3, 0xe4, 0xf6, 0xb3, 0x9d,
	0x3e, 0xdd, 0xf3, 0xc5, 0x5b, 0xf2, 0x07, 0x19, 0x79, 0x46, 0xe8, 0x4b, 0x08, 0xdd, 0x2a, 0xd0,
	0xc7, 0x9b, 0x83, 0x83, 0x0d, 0x9c, 0x5e, 0xff, 0x4d, 0x6f, 0x89, 0x6f, 0x21, 0xc9, 0x77, 0x23,
	0xe4, 0x07, 0x23, 0xe4, 0x7b, 0x23, 0xbc, 0x86, 0x08, 0x87, 0x41, 0x07, 0x66, 0xc3, 0xbb, 0x98,
	0x3e, 0xd9, 0xe1, 0x87, 0xfa, 0x2f, 0x31, 0x7e, 0x7a, 0xfe, 0x27, 0x00, 0x00, 0xff, 0xff, 0x97,
	0xad, 0xd1, 0x41, 0xd1, 0x04, 0x00, 0x00,
}
