#!/bin/bash

if [ -z "$1" ] ; then
	echo "Requires IP address to listen on."
	exit
fi

export PATH=${PATH}:/usr/local/bin:/home/gholt/bin

cd /etc/cfsd

ring cfs.builder add address0=${1}:12300 \
                     address1=${1}:12310 address2=${1}:12311 \
                     address3=${1}:12320 address4=${1}:12321
ring cfs.builder ring
