#! /bin/sh

### BEGIN INIT INFO
# Provides:          oort-valued
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: oort-valued
### END INIT INFO

DAEMON_OPTS="-s map"
APP="/usr/local/bin/oort-valued"

pid() {
  if [ -f /usr/local/bin/$APP ]; then
    pidof /usr/local/bin/$APP
  fi
}

stop() {
  if pidof /usr/local/bin/$APP >/dev/null; then
    kill "$(pid)"
  else
    echo "$APP not running"
    exit 1
  fi
}

start() {
  [ -f /etc/default/cfsd ] && . /etc/default/cfd
  if pidof /usr/local/bin/$APP >/dev/null; then
    echo "$APP already running"
    exit 1
  else
    nohup $APP $DAEMON_OPTS > /var/log/$APP.log  2>&1 &
  fi
}

restart() {
  [ -f /etc/default/cfsd ] && . /etc/default/cfd
  if pidof /usr/local/bin/$APP >/dev/null; then
    kill  "$(pid)"
    nohup $APP $DAEMON_OPTS > /var/log/$APP.log  2>&1 &
    exit 0
  else
    nohup $APP $DAEMON_OPTS > /var/log/$APP.log  2>&1 &
    exit 0
  fi
}

status() {
  if pidof /usr/local/bin/$APP >/dev/null; then
    echo "$APP with pid $(pid) is running"
  else
    echo "$APP is not running"
  fi
  exit 0
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        restart
        ;;
  status)
        status
        ;;
  *)
        echo "Usage: service $APP {start|stop|restart|status}"
        exit 1
        ;;
esac
