[OortValueStoreConfig]
InsecureSkipVerify = true
CertFile = "/etc/cfsd/server.crt"
KeyFile = "/etc/cfsd/server.key"
MetricsAddr = ":9300"

[ValueStoreConfig]
Scale = 0.5
CompactionInterval = 42
ValueCap = 4194302
Path = "/var/lib/cfsd"

[OortGroupStoreConfig]
InsecureSkipVerify = true
CertFile = "/etc/cfsd/server.crt"
KeyFile = "/etc/cfsd/server.key"
MetricsAddr = ":9200"

[GroupStoreConfig]
Scale = 0.5
CompactionInterval = 42
ValueCap = 4194302
Path = "/var/lib/cfsd"

[TCPMsgRingConfig]
UseTLS = true
CertFile = "/etc/cfsd/server.crt"
KeyFile = "/etc/cfsd/server.key"
