// Code generated by protoc-gen-go.
// source: formic_api.proto
// DO NOT EDIT!

/*
Package formicproto is a generated protocol buffer package.

It is generated from these files:
	formic_api.proto

It has these top-level messages:
	Attr
	SymlinkRequest
	SymlinkResponse
	ReadlinkRequest
	ReadlinkResponse
	GetxattrRequest
	GetxattrResponse
	SetxattrRequest
	SetxattrResponse
	ListxattrRequest
	ListxattrResponse
	RemovexattrRequest
	RemovexattrResponse
	RenameRequest
	RenameResponse
	StatfsRequest
	StatfsResponse
	InitFsRequest
	InitFsResponse
	CheckRequest
	CheckResponse
	InodeEntry
	Tombstone
	Dirty
	FileBlock
	ModFS
	CreateFSRequest
	CreateFSResponse
	ListFSRequest
	ListFSResponse
	ShowFSRequest
	ShowFSResponse
	DeleteFSRequest
	DeleteFSResponse
	UpdateFSRequest
	UpdateFSResponse
	GrantAddrFSRequest
	GrantAddrFSResponse
	RevokeAddrFSRequest
	RevokeAddrFSResponse
	DirEntry
*/
package formicproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Attr
type Attr struct {
	Inode  uint64 `protobuf:"varint,1,opt,name=inode" json:"inode,omitempty"`
	Atime  int64  `protobuf:"varint,2,opt,name=atime" json:"atime,omitempty"`
	Mtime  int64  `protobuf:"varint,3,opt,name=mtime" json:"mtime,omitempty"`
	Ctime  int64  `protobuf:"varint,4,opt,name=ctime" json:"ctime,omitempty"`
	Crtime int64  `protobuf:"varint,5,opt,name=crtime" json:"crtime,omitempty"`
	Mode   uint32 `protobuf:"varint,6,opt,name=mode" json:"mode,omitempty"`
	Valid  int32  `protobuf:"varint,7,opt,name=valid" json:"valid,omitempty"`
	Size   uint64 `protobuf:"varint,8,opt,name=size" json:"size,omitempty"`
	Uid    uint32 `protobuf:"varint,9,opt,name=uid" json:"uid,omitempty"`
	Gid    uint32 `protobuf:"varint,10,opt,name=gid" json:"gid,omitempty"`
}

func (m *Attr) Reset()                    { *m = Attr{} }
func (m *Attr) String() string            { return proto.CompactTextString(m) }
func (*Attr) ProtoMessage()               {}
func (*Attr) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Attr) GetInode() uint64 {
	if m != nil {
		return m.Inode
	}
	return 0
}

func (m *Attr) GetAtime() int64 {
	if m != nil {
		return m.Atime
	}
	return 0
}

func (m *Attr) GetMtime() int64 {
	if m != nil {
		return m.Mtime
	}
	return 0
}

func (m *Attr) GetCtime() int64 {
	if m != nil {
		return m.Ctime
	}
	return 0
}

func (m *Attr) GetCrtime() int64 {
	if m != nil {
		return m.Crtime
	}
	return 0
}

func (m *Attr) GetMode() uint32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

func (m *Attr) GetValid() int32 {
	if m != nil {
		return m.Valid
	}
	return 0
}

func (m *Attr) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Attr) GetUid() uint32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *Attr) GetGid() uint32 {
	if m != nil {
		return m.Gid
	}
	return 0
}

// SymlinkRequest
type SymlinkRequest struct {
	Parent uint64 `protobuf:"varint,1,opt,name=parent" json:"parent,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Target string `protobuf:"bytes,3,opt,name=target" json:"target,omitempty"`
	Uid    uint32 `protobuf:"varint,4,opt,name=uid" json:"uid,omitempty"`
	Gid    uint32 `protobuf:"varint,5,opt,name=gid" json:"gid,omitempty"`
}

func (m *SymlinkRequest) Reset()                    { *m = SymlinkRequest{} }
func (m *SymlinkRequest) String() string            { return proto.CompactTextString(m) }
func (*SymlinkRequest) ProtoMessage()               {}
func (*SymlinkRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SymlinkRequest) GetParent() uint64 {
	if m != nil {
		return m.Parent
	}
	return 0
}

func (m *SymlinkRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SymlinkRequest) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *SymlinkRequest) GetUid() uint32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *SymlinkRequest) GetGid() uint32 {
	if m != nil {
		return m.Gid
	}
	return 0
}

// SymlinkResponse
type SymlinkResponse struct {
	Parent uint64 `protobuf:"varint,1,opt,name=parent" json:"parent,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Attr   *Attr  `protobuf:"bytes,3,opt,name=attr" json:"attr,omitempty"`
}

func (m *SymlinkResponse) Reset()                    { *m = SymlinkResponse{} }
func (m *SymlinkResponse) String() string            { return proto.CompactTextString(m) }
func (*SymlinkResponse) ProtoMessage()               {}
func (*SymlinkResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SymlinkResponse) GetParent() uint64 {
	if m != nil {
		return m.Parent
	}
	return 0
}

func (m *SymlinkResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SymlinkResponse) GetAttr() *Attr {
	if m != nil {
		return m.Attr
	}
	return nil
}

// ReadlinkRequest
type ReadlinkRequest struct {
	Inode uint64 `protobuf:"varint,1,opt,name=inode" json:"inode,omitempty"`
}

func (m *ReadlinkRequest) Reset()                    { *m = ReadlinkRequest{} }
func (m *ReadlinkRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadlinkRequest) ProtoMessage()               {}
func (*ReadlinkRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReadlinkRequest) GetInode() uint64 {
	if m != nil {
		return m.Inode
	}
	return 0
}

// ReadlinkResponse
type ReadlinkResponse struct {
	Target string `protobuf:"bytes,1,opt,name=target" json:"target,omitempty"`
}

func (m *ReadlinkResponse) Reset()                    { *m = ReadlinkResponse{} }
func (m *ReadlinkResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadlinkResponse) ProtoMessage()               {}
func (*ReadlinkResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ReadlinkResponse) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

// Getxattr
type GetxattrRequest struct {
	Inode    uint64 `protobuf:"varint,1,opt,name=inode" json:"inode,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Size     uint32 `protobuf:"varint,3,opt,name=size" json:"size,omitempty"`
	Position uint32 `protobuf:"varint,4,opt,name=position" json:"position,omitempty"`
}

func (m *GetxattrRequest) Reset()                    { *m = GetxattrRequest{} }
func (m *GetxattrRequest) String() string            { return proto.CompactTextString(m) }
func (*GetxattrRequest) ProtoMessage()               {}
func (*GetxattrRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetxattrRequest) GetInode() uint64 {
	if m != nil {
		return m.Inode
	}
	return 0
}

func (m *GetxattrRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetxattrRequest) GetSize() uint32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *GetxattrRequest) GetPosition() uint32 {
	if m != nil {
		return m.Position
	}
	return 0
}

type GetxattrResponse struct {
	Xattr []byte `protobuf:"bytes,1,opt,name=xattr,proto3" json:"xattr,omitempty"`
}

func (m *GetxattrResponse) Reset()                    { *m = GetxattrResponse{} }
func (m *GetxattrResponse) String() string            { return proto.CompactTextString(m) }
func (*GetxattrResponse) ProtoMessage()               {}
func (*GetxattrResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetxattrResponse) GetXattr() []byte {
	if m != nil {
		return m.Xattr
	}
	return nil
}

// Setxattr
type SetxattrRequest struct {
	Inode    uint64 `protobuf:"varint,1,opt,name=inode" json:"inode,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Value    []byte `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Position uint32 `protobuf:"varint,4,opt,name=position" json:"position,omitempty"`
	Flags    uint32 `protobuf:"varint,5,opt,name=flags" json:"flags,omitempty"`
}

func (m *SetxattrRequest) Reset()                    { *m = SetxattrRequest{} }
func (m *SetxattrRequest) String() string            { return proto.CompactTextString(m) }
func (*SetxattrRequest) ProtoMessage()               {}
func (*SetxattrRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *SetxattrRequest) GetInode() uint64 {
	if m != nil {
		return m.Inode
	}
	return 0
}

func (m *SetxattrRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SetxattrRequest) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *SetxattrRequest) GetPosition() uint32 {
	if m != nil {
		return m.Position
	}
	return 0
}

func (m *SetxattrRequest) GetFlags() uint32 {
	if m != nil {
		return m.Flags
	}
	return 0
}

type SetxattrResponse struct {
}

func (m *SetxattrResponse) Reset()                    { *m = SetxattrResponse{} }
func (m *SetxattrResponse) String() string            { return proto.CompactTextString(m) }
func (*SetxattrResponse) ProtoMessage()               {}
func (*SetxattrResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

// Listxattr
type ListxattrRequest struct {
	Inode    uint64 `protobuf:"varint,1,opt,name=inode" json:"inode,omitempty"`
	Size     uint32 `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
	Position uint32 `protobuf:"varint,3,opt,name=position" json:"position,omitempty"`
}

func (m *ListxattrRequest) Reset()                    { *m = ListxattrRequest{} }
func (m *ListxattrRequest) String() string            { return proto.CompactTextString(m) }
func (*ListxattrRequest) ProtoMessage()               {}
func (*ListxattrRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *ListxattrRequest) GetInode() uint64 {
	if m != nil {
		return m.Inode
	}
	return 0
}

func (m *ListxattrRequest) GetSize() uint32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ListxattrRequest) GetPosition() uint32 {
	if m != nil {
		return m.Position
	}
	return 0
}

type ListxattrResponse struct {
	Xattr []byte `protobuf:"bytes,1,opt,name=xattr,proto3" json:"xattr,omitempty"`
}

func (m *ListxattrResponse) Reset()                    { *m = ListxattrResponse{} }
func (m *ListxattrResponse) String() string            { return proto.CompactTextString(m) }
func (*ListxattrResponse) ProtoMessage()               {}
func (*ListxattrResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *ListxattrResponse) GetXattr() []byte {
	if m != nil {
		return m.Xattr
	}
	return nil
}

// Removexattr
type RemovexattrRequest struct {
	Inode uint64 `protobuf:"varint,1,opt,name=inode" json:"inode,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *RemovexattrRequest) Reset()                    { *m = RemovexattrRequest{} }
func (m *RemovexattrRequest) String() string            { return proto.CompactTextString(m) }
func (*RemovexattrRequest) ProtoMessage()               {}
func (*RemovexattrRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *RemovexattrRequest) GetInode() uint64 {
	if m != nil {
		return m.Inode
	}
	return 0
}

func (m *RemovexattrRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type RemovexattrResponse struct {
}

func (m *RemovexattrResponse) Reset()                    { *m = RemovexattrResponse{} }
func (m *RemovexattrResponse) String() string            { return proto.CompactTextString(m) }
func (*RemovexattrResponse) ProtoMessage()               {}
func (*RemovexattrResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

// Rename
type RenameRequest struct {
	OldParent uint64 `protobuf:"varint,1,opt,name=oldParent" json:"oldParent,omitempty"`
	NewParent uint64 `protobuf:"varint,2,opt,name=newParent" json:"newParent,omitempty"`
	OldName   string `protobuf:"bytes,3,opt,name=oldName" json:"oldName,omitempty"`
	NewName   string `protobuf:"bytes,4,opt,name=newName" json:"newName,omitempty"`
}

func (m *RenameRequest) Reset()                    { *m = RenameRequest{} }
func (m *RenameRequest) String() string            { return proto.CompactTextString(m) }
func (*RenameRequest) ProtoMessage()               {}
func (*RenameRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *RenameRequest) GetOldParent() uint64 {
	if m != nil {
		return m.OldParent
	}
	return 0
}

func (m *RenameRequest) GetNewParent() uint64 {
	if m != nil {
		return m.NewParent
	}
	return 0
}

func (m *RenameRequest) GetOldName() string {
	if m != nil {
		return m.OldName
	}
	return ""
}

func (m *RenameRequest) GetNewName() string {
	if m != nil {
		return m.NewName
	}
	return ""
}

type RenameResponse struct {
}

func (m *RenameResponse) Reset()                    { *m = RenameResponse{} }
func (m *RenameResponse) String() string            { return proto.CompactTextString(m) }
func (*RenameResponse) ProtoMessage()               {}
func (*RenameResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

// Statfs
type StatfsRequest struct {
}

func (m *StatfsRequest) Reset()                    { *m = StatfsRequest{} }
func (m *StatfsRequest) String() string            { return proto.CompactTextString(m) }
func (*StatfsRequest) ProtoMessage()               {}
func (*StatfsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

type StatfsResponse struct {
	Blocks  uint64 `protobuf:"varint,1,opt,name=blocks" json:"blocks,omitempty"`
	Bfree   uint64 `protobuf:"varint,2,opt,name=bfree" json:"bfree,omitempty"`
	Bavail  uint64 `protobuf:"varint,3,opt,name=bavail" json:"bavail,omitempty"`
	Files   uint64 `protobuf:"varint,4,opt,name=files" json:"files,omitempty"`
	Ffree   uint64 `protobuf:"varint,5,opt,name=ffree" json:"ffree,omitempty"`
	Bsize   uint32 `protobuf:"varint,6,opt,name=bsize" json:"bsize,omitempty"`
	Namelen uint32 `protobuf:"varint,7,opt,name=namelen" json:"namelen,omitempty"`
	Frsize  uint32 `protobuf:"varint,8,opt,name=frsize" json:"frsize,omitempty"`
}

func (m *StatfsResponse) Reset()                    { *m = StatfsResponse{} }
func (m *StatfsResponse) String() string            { return proto.CompactTextString(m) }
func (*StatfsResponse) ProtoMessage()               {}
func (*StatfsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *StatfsResponse) GetBlocks() uint64 {
	if m != nil {
		return m.Blocks
	}
	return 0
}

func (m *StatfsResponse) GetBfree() uint64 {
	if m != nil {
		return m.Bfree
	}
	return 0
}

func (m *StatfsResponse) GetBavail() uint64 {
	if m != nil {
		return m.Bavail
	}
	return 0
}

func (m *StatfsResponse) GetFiles() uint64 {
	if m != nil {
		return m.Files
	}
	return 0
}

func (m *StatfsResponse) GetFfree() uint64 {
	if m != nil {
		return m.Ffree
	}
	return 0
}

func (m *StatfsResponse) GetBsize() uint32 {
	if m != nil {
		return m.Bsize
	}
	return 0
}

func (m *StatfsResponse) GetNamelen() uint32 {
	if m != nil {
		return m.Namelen
	}
	return 0
}

func (m *StatfsResponse) GetFrsize() uint32 {
	if m != nil {
		return m.Frsize
	}
	return 0
}

// InitFs
type InitFsRequest struct {
}

func (m *InitFsRequest) Reset()                    { *m = InitFsRequest{} }
func (m *InitFsRequest) String() string            { return proto.CompactTextString(m) }
func (*InitFsRequest) ProtoMessage()               {}
func (*InitFsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

type InitFsResponse struct {
}

func (m *InitFsResponse) Reset()                    { *m = InitFsResponse{} }
func (m *InitFsResponse) String() string            { return proto.CompactTextString(m) }
func (*InitFsResponse) ProtoMessage()               {}
func (*InitFsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

// Check
type CheckRequest struct {
	Inode uint64 `protobuf:"varint,1,opt,name=inode" json:"inode,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *CheckRequest) Reset()                    { *m = CheckRequest{} }
func (m *CheckRequest) String() string            { return proto.CompactTextString(m) }
func (*CheckRequest) ProtoMessage()               {}
func (*CheckRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *CheckRequest) GetInode() uint64 {
	if m != nil {
		return m.Inode
	}
	return 0
}

func (m *CheckRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CheckResponse struct {
	Response string `protobuf:"bytes,1,opt,name=response" json:"response,omitempty"`
}

func (m *CheckResponse) Reset()                    { *m = CheckResponse{} }
func (m *CheckResponse) String() string            { return proto.CompactTextString(m) }
func (*CheckResponse) ProtoMessage()               {}
func (*CheckResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *CheckResponse) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

// Inode
// This is used for serialization of the inode metadata
// This is *not* used for api calls
type InodeEntry struct {
	Version   uint32            `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	IsDir     bool              `protobuf:"varint,2,opt,name=isDir" json:"isDir,omitempty"`
	Attr      *Attr             `protobuf:"bytes,3,opt,name=attr" json:"attr,omitempty"`
	Parent    uint64            `protobuf:"varint,4,opt,name=parent" json:"parent,omitempty"`
	Inode     uint64            `protobuf:"varint,5,opt,name=inode" json:"inode,omitempty"`
	NodeCount uint64            `protobuf:"varint,6,opt,name=nodeCount" json:"nodeCount,omitempty"`
	IsLink    bool              `protobuf:"varint,7,opt,name=isLink" json:"isLink,omitempty"`
	Target    string            `protobuf:"bytes,8,opt,name=target" json:"target,omitempty"`
	Xattr     map[string][]byte `protobuf:"bytes,9,rep,name=xattr" json:"xattr,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Blocks    uint64            `protobuf:"varint,10,opt,name=blocks" json:"blocks,omitempty"`
	BlockSize uint64            `protobuf:"varint,11,opt,name=blockSize" json:"blockSize,omitempty"`
	FsId      []byte            `protobuf:"bytes,13,opt,name=fsId,proto3" json:"fsId,omitempty"`
}

func (m *InodeEntry) Reset()                    { *m = InodeEntry{} }
func (m *InodeEntry) String() string            { return proto.CompactTextString(m) }
func (*InodeEntry) ProtoMessage()               {}
func (*InodeEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *InodeEntry) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *InodeEntry) GetIsDir() bool {
	if m != nil {
		return m.IsDir
	}
	return false
}

func (m *InodeEntry) GetAttr() *Attr {
	if m != nil {
		return m.Attr
	}
	return nil
}

func (m *InodeEntry) GetParent() uint64 {
	if m != nil {
		return m.Parent
	}
	return 0
}

func (m *InodeEntry) GetInode() uint64 {
	if m != nil {
		return m.Inode
	}
	return 0
}

func (m *InodeEntry) GetNodeCount() uint64 {
	if m != nil {
		return m.NodeCount
	}
	return 0
}

func (m *InodeEntry) GetIsLink() bool {
	if m != nil {
		return m.IsLink
	}
	return false
}

func (m *InodeEntry) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *InodeEntry) GetXattr() map[string][]byte {
	if m != nil {
		return m.Xattr
	}
	return nil
}

func (m *InodeEntry) GetBlocks() uint64 {
	if m != nil {
		return m.Blocks
	}
	return 0
}

func (m *InodeEntry) GetBlockSize() uint64 {
	if m != nil {
		return m.BlockSize
	}
	return 0
}

func (m *InodeEntry) GetFsId() []byte {
	if m != nil {
		return m.FsId
	}
	return nil
}

// Tombstone
// Stores information needed to keep track of deleted items
type Tombstone struct {
	Dtime  int64  `protobuf:"varint,1,opt,name=dtime" json:"dtime,omitempty"`
	Qtime  int64  `protobuf:"varint,2,opt,name=qtime" json:"qtime,omitempty"`
	FsId   []byte `protobuf:"bytes,3,opt,name=fsId,proto3" json:"fsId,omitempty"`
	Inode  uint64 `protobuf:"varint,4,opt,name=inode" json:"inode,omitempty"`
	Blocks uint64 `protobuf:"varint,5,opt,name=blocks" json:"blocks,omitempty"`
}

func (m *Tombstone) Reset()                    { *m = Tombstone{} }
func (m *Tombstone) String() string            { return proto.CompactTextString(m) }
func (*Tombstone) ProtoMessage()               {}
func (*Tombstone) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *Tombstone) GetDtime() int64 {
	if m != nil {
		return m.Dtime
	}
	return 0
}

func (m *Tombstone) GetQtime() int64 {
	if m != nil {
		return m.Qtime
	}
	return 0
}

func (m *Tombstone) GetFsId() []byte {
	if m != nil {
		return m.FsId
	}
	return nil
}

func (m *Tombstone) GetInode() uint64 {
	if m != nil {
		return m.Inode
	}
	return 0
}

func (m *Tombstone) GetBlocks() uint64 {
	if m != nil {
		return m.Blocks
	}
	return 0
}

// Dirty
// Stores information needed to keep track of dirty items
type Dirty struct {
	Dtime  int64  `protobuf:"varint,1,opt,name=dtime" json:"dtime,omitempty"`
	Qtime  int64  `protobuf:"varint,2,opt,name=qtime" json:"qtime,omitempty"`
	FsId   []byte `protobuf:"bytes,3,opt,name=fsId,proto3" json:"fsId,omitempty"`
	Inode  uint64 `protobuf:"varint,4,opt,name=inode" json:"inode,omitempty"`
	Blocks uint64 `protobuf:"varint,5,opt,name=blocks" json:"blocks,omitempty"`
}

func (m *Dirty) Reset()                    { *m = Dirty{} }
func (m *Dirty) String() string            { return proto.CompactTextString(m) }
func (*Dirty) ProtoMessage()               {}
func (*Dirty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *Dirty) GetDtime() int64 {
	if m != nil {
		return m.Dtime
	}
	return 0
}

func (m *Dirty) GetQtime() int64 {
	if m != nil {
		return m.Qtime
	}
	return 0
}

func (m *Dirty) GetFsId() []byte {
	if m != nil {
		return m.FsId
	}
	return nil
}

func (m *Dirty) GetInode() uint64 {
	if m != nil {
		return m.Inode
	}
	return 0
}

func (m *Dirty) GetBlocks() uint64 {
	if m != nil {
		return m.Blocks
	}
	return 0
}

// FileBlock
// This is used for storing blocks in value store
// This is *not* used for api calls
type FileBlock struct {
	Version  uint32 `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Data     []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Checksum uint32 `protobuf:"varint,3,opt,name=checksum" json:"checksum,omitempty"`
}

func (m *FileBlock) Reset()                    { *m = FileBlock{} }
func (m *FileBlock) String() string            { return proto.CompactTextString(m) }
func (*FileBlock) ProtoMessage()               {}
func (*FileBlock) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *FileBlock) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *FileBlock) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *FileBlock) GetChecksum() uint32 {
	if m != nil {
		return m.Checksum
	}
	return 0
}

// ModFS ...
type ModFS struct {
	Name   string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Status string `protobuf:"bytes,2,opt,name=Status" json:"Status,omitempty"`
}

func (m *ModFS) Reset()                    { *m = ModFS{} }
func (m *ModFS) String() string            { return proto.CompactTextString(m) }
func (*ModFS) ProtoMessage()               {}
func (*ModFS) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *ModFS) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ModFS) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

// Request to create a new filesystem
type CreateFSRequest struct {
	Token  string `protobuf:"bytes,1,opt,name=Token" json:"Token,omitempty"`
	FSName string `protobuf:"bytes,2,opt,name=FSName" json:"FSName,omitempty"`
}

func (m *CreateFSRequest) Reset()                    { *m = CreateFSRequest{} }
func (m *CreateFSRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateFSRequest) ProtoMessage()               {}
func (*CreateFSRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *CreateFSRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *CreateFSRequest) GetFSName() string {
	if m != nil {
		return m.FSName
	}
	return ""
}

// Response from creating a new filesystem
type CreateFSResponse struct {
	Data string `protobuf:"bytes,1,opt,name=Data" json:"Data,omitempty"`
}

func (m *CreateFSResponse) Reset()                    { *m = CreateFSResponse{} }
func (m *CreateFSResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateFSResponse) ProtoMessage()               {}
func (*CreateFSResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *CreateFSResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

// Request a list of all file systems for a given account
type ListFSRequest struct {
	Token string `protobuf:"bytes,1,opt,name=Token" json:"Token,omitempty"`
}

func (m *ListFSRequest) Reset()                    { *m = ListFSRequest{} }
func (m *ListFSRequest) String() string            { return proto.CompactTextString(m) }
func (*ListFSRequest) ProtoMessage()               {}
func (*ListFSRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *ListFSRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

// Response for displaying a list of all an accounts file systems.
type ListFSResponse struct {
	Data string `protobuf:"bytes,1,opt,name=Data" json:"Data,omitempty"`
}

func (m *ListFSResponse) Reset()                    { *m = ListFSResponse{} }
func (m *ListFSResponse) String() string            { return proto.CompactTextString(m) }
func (*ListFSResponse) ProtoMessage()               {}
func (*ListFSResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *ListFSResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

// Request to show the specific details about a file system
type ShowFSRequest struct {
	Token string `protobuf:"bytes,1,opt,name=Token" json:"Token,omitempty"`
	FSid  string `protobuf:"bytes,2,opt,name=FSid" json:"FSid,omitempty"`
}

func (m *ShowFSRequest) Reset()                    { *m = ShowFSRequest{} }
func (m *ShowFSRequest) String() string            { return proto.CompactTextString(m) }
func (*ShowFSRequest) ProtoMessage()               {}
func (*ShowFSRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

func (m *ShowFSRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ShowFSRequest) GetFSid() string {
	if m != nil {
		return m.FSid
	}
	return ""
}

// Response for a specific file system for an account.
type ShowFSResponse struct {
	Data string `protobuf:"bytes,1,opt,name=Data" json:"Data,omitempty"`
}

func (m *ShowFSResponse) Reset()                    { *m = ShowFSResponse{} }
func (m *ShowFSResponse) String() string            { return proto.CompactTextString(m) }
func (*ShowFSResponse) ProtoMessage()               {}
func (*ShowFSResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

func (m *ShowFSResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

// Request to delete a specific file system
type DeleteFSRequest struct {
	Token string `protobuf:"bytes,1,opt,name=Token" json:"Token,omitempty"`
	FSid  string `protobuf:"bytes,2,opt,name=FSid" json:"FSid,omitempty"`
}

func (m *DeleteFSRequest) Reset()                    { *m = DeleteFSRequest{} }
func (m *DeleteFSRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteFSRequest) ProtoMessage()               {}
func (*DeleteFSRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32} }

func (m *DeleteFSRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *DeleteFSRequest) GetFSid() string {
	if m != nil {
		return m.FSid
	}
	return ""
}

// Response from deleting a file system
type DeleteFSResponse struct {
	Data string `protobuf:"bytes,1,opt,name=Data" json:"Data,omitempty"`
}

func (m *DeleteFSResponse) Reset()                    { *m = DeleteFSResponse{} }
func (m *DeleteFSResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteFSResponse) ProtoMessage()               {}
func (*DeleteFSResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{33} }

func (m *DeleteFSResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

// Request to update a specific file system's information
type UpdateFSRequest struct {
	Token   string `protobuf:"bytes,1,opt,name=Token" json:"Token,omitempty"`
	FSid    string `protobuf:"bytes,2,opt,name=FSid" json:"FSid,omitempty"`
	Filesys *ModFS `protobuf:"bytes,3,opt,name=Filesys" json:"Filesys,omitempty"`
}

func (m *UpdateFSRequest) Reset()                    { *m = UpdateFSRequest{} }
func (m *UpdateFSRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateFSRequest) ProtoMessage()               {}
func (*UpdateFSRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{34} }

func (m *UpdateFSRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *UpdateFSRequest) GetFSid() string {
	if m != nil {
		return m.FSid
	}
	return ""
}

func (m *UpdateFSRequest) GetFilesys() *ModFS {
	if m != nil {
		return m.Filesys
	}
	return nil
}

// Response from an update operation
type UpdateFSResponse struct {
	Data string `protobuf:"bytes,1,opt,name=Data" json:"Data,omitempty"`
}

func (m *UpdateFSResponse) Reset()                    { *m = UpdateFSResponse{} }
func (m *UpdateFSResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateFSResponse) ProtoMessage()               {}
func (*UpdateFSResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{35} }

func (m *UpdateFSResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

// Request grant an ip address access to a file system
type GrantAddrFSRequest struct {
	Token string `protobuf:"bytes,1,opt,name=Token" json:"Token,omitempty"`
	FSid  string `protobuf:"bytes,2,opt,name=FSid" json:"FSid,omitempty"`
	Addr  string `protobuf:"bytes,3,opt,name=Addr" json:"Addr,omitempty"`
}

func (m *GrantAddrFSRequest) Reset()                    { *m = GrantAddrFSRequest{} }
func (m *GrantAddrFSRequest) String() string            { return proto.CompactTextString(m) }
func (*GrantAddrFSRequest) ProtoMessage()               {}
func (*GrantAddrFSRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{36} }

func (m *GrantAddrFSRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *GrantAddrFSRequest) GetFSid() string {
	if m != nil {
		return m.FSid
	}
	return ""
}

func (m *GrantAddrFSRequest) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

// Response from granting ip address access to a file system
type GrantAddrFSResponse struct {
	Data string `protobuf:"bytes,1,opt,name=Data" json:"Data,omitempty"`
}

func (m *GrantAddrFSResponse) Reset()                    { *m = GrantAddrFSResponse{} }
func (m *GrantAddrFSResponse) String() string            { return proto.CompactTextString(m) }
func (*GrantAddrFSResponse) ProtoMessage()               {}
func (*GrantAddrFSResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{37} }

func (m *GrantAddrFSResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

// Request revoke an ip address access to a file system
type RevokeAddrFSRequest struct {
	Token string `protobuf:"bytes,1,opt,name=Token" json:"Token,omitempty"`
	FSid  string `protobuf:"bytes,2,opt,name=FSid" json:"FSid,omitempty"`
	Addr  string `protobuf:"bytes,3,opt,name=Addr" json:"Addr,omitempty"`
}

func (m *RevokeAddrFSRequest) Reset()                    { *m = RevokeAddrFSRequest{} }
func (m *RevokeAddrFSRequest) String() string            { return proto.CompactTextString(m) }
func (*RevokeAddrFSRequest) ProtoMessage()               {}
func (*RevokeAddrFSRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{38} }

func (m *RevokeAddrFSRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *RevokeAddrFSRequest) GetFSid() string {
	if m != nil {
		return m.FSid
	}
	return ""
}

func (m *RevokeAddrFSRequest) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

// Response from revoking ip address access to a file system
type RevokeAddrFSResponse struct {
	Data string `protobuf:"bytes,1,opt,name=Data" json:"Data,omitempty"`
}

func (m *RevokeAddrFSResponse) Reset()                    { *m = RevokeAddrFSResponse{} }
func (m *RevokeAddrFSResponse) String() string            { return proto.CompactTextString(m) }
func (*RevokeAddrFSResponse) ProtoMessage()               {}
func (*RevokeAddrFSResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{39} }

func (m *RevokeAddrFSResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

// TODO: Needed for now since this is used when storing in the stores.
// This really shouldn't be in this proto package.
// This is used for the serialization of dir info in the group score
// This is *not* used for api calls
type DirEntry struct {
	Version   uint32     `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Name      string     `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Id        []byte     `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Tombstone *Tombstone `protobuf:"bytes,4,opt,name=tombstone" json:"tombstone,omitempty"`
	Type      uint32     `protobuf:"varint,5,opt,name=type" json:"type,omitempty"`
}

func (m *DirEntry) Reset()                    { *m = DirEntry{} }
func (m *DirEntry) String() string            { return proto.CompactTextString(m) }
func (*DirEntry) ProtoMessage()               {}
func (*DirEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{40} }

func (m *DirEntry) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *DirEntry) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DirEntry) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *DirEntry) GetTombstone() *Tombstone {
	if m != nil {
		return m.Tombstone
	}
	return nil
}

func (m *DirEntry) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func init() {
	proto.RegisterType((*Attr)(nil), "formicproto.Attr")
	proto.RegisterType((*SymlinkRequest)(nil), "formicproto.SymlinkRequest")
	proto.RegisterType((*SymlinkResponse)(nil), "formicproto.SymlinkResponse")
	proto.RegisterType((*ReadlinkRequest)(nil), "formicproto.ReadlinkRequest")
	proto.RegisterType((*ReadlinkResponse)(nil), "formicproto.ReadlinkResponse")
	proto.RegisterType((*GetxattrRequest)(nil), "formicproto.GetxattrRequest")
	proto.RegisterType((*GetxattrResponse)(nil), "formicproto.GetxattrResponse")
	proto.RegisterType((*SetxattrRequest)(nil), "formicproto.SetxattrRequest")
	proto.RegisterType((*SetxattrResponse)(nil), "formicproto.SetxattrResponse")
	proto.RegisterType((*ListxattrRequest)(nil), "formicproto.ListxattrRequest")
	proto.RegisterType((*ListxattrResponse)(nil), "formicproto.ListxattrResponse")
	proto.RegisterType((*RemovexattrRequest)(nil), "formicproto.RemovexattrRequest")
	proto.RegisterType((*RemovexattrResponse)(nil), "formicproto.RemovexattrResponse")
	proto.RegisterType((*RenameRequest)(nil), "formicproto.RenameRequest")
	proto.RegisterType((*RenameResponse)(nil), "formicproto.RenameResponse")
	proto.RegisterType((*StatfsRequest)(nil), "formicproto.StatfsRequest")
	proto.RegisterType((*StatfsResponse)(nil), "formicproto.StatfsResponse")
	proto.RegisterType((*InitFsRequest)(nil), "formicproto.InitFsRequest")
	proto.RegisterType((*InitFsResponse)(nil), "formicproto.InitFsResponse")
	proto.RegisterType((*CheckRequest)(nil), "formicproto.CheckRequest")
	proto.RegisterType((*CheckResponse)(nil), "formicproto.CheckResponse")
	proto.RegisterType((*InodeEntry)(nil), "formicproto.InodeEntry")
	proto.RegisterType((*Tombstone)(nil), "formicproto.Tombstone")
	proto.RegisterType((*Dirty)(nil), "formicproto.Dirty")
	proto.RegisterType((*FileBlock)(nil), "formicproto.FileBlock")
	proto.RegisterType((*ModFS)(nil), "formicproto.ModFS")
	proto.RegisterType((*CreateFSRequest)(nil), "formicproto.CreateFSRequest")
	proto.RegisterType((*CreateFSResponse)(nil), "formicproto.CreateFSResponse")
	proto.RegisterType((*ListFSRequest)(nil), "formicproto.ListFSRequest")
	proto.RegisterType((*ListFSResponse)(nil), "formicproto.ListFSResponse")
	proto.RegisterType((*ShowFSRequest)(nil), "formicproto.ShowFSRequest")
	proto.RegisterType((*ShowFSResponse)(nil), "formicproto.ShowFSResponse")
	proto.RegisterType((*DeleteFSRequest)(nil), "formicproto.DeleteFSRequest")
	proto.RegisterType((*DeleteFSResponse)(nil), "formicproto.DeleteFSResponse")
	proto.RegisterType((*UpdateFSRequest)(nil), "formicproto.UpdateFSRequest")
	proto.RegisterType((*UpdateFSResponse)(nil), "formicproto.UpdateFSResponse")
	proto.RegisterType((*GrantAddrFSRequest)(nil), "formicproto.GrantAddrFSRequest")
	proto.RegisterType((*GrantAddrFSResponse)(nil), "formicproto.GrantAddrFSResponse")
	proto.RegisterType((*RevokeAddrFSRequest)(nil), "formicproto.RevokeAddrFSRequest")
	proto.RegisterType((*RevokeAddrFSResponse)(nil), "formicproto.RevokeAddrFSResponse")
	proto.RegisterType((*DirEntry)(nil), "formicproto.DirEntry")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Api service

type ApiClient interface {
	Symlink(ctx context.Context, in *SymlinkRequest, opts ...grpc.CallOption) (*SymlinkResponse, error)
	Readlink(ctx context.Context, in *ReadlinkRequest, opts ...grpc.CallOption) (*ReadlinkResponse, error)
	Getxattr(ctx context.Context, in *GetxattrRequest, opts ...grpc.CallOption) (*GetxattrResponse, error)
	Setxattr(ctx context.Context, in *SetxattrRequest, opts ...grpc.CallOption) (*SetxattrResponse, error)
	Listxattr(ctx context.Context, in *ListxattrRequest, opts ...grpc.CallOption) (*ListxattrResponse, error)
	Removexattr(ctx context.Context, in *RemovexattrRequest, opts ...grpc.CallOption) (*RemovexattrResponse, error)
	Rename(ctx context.Context, in *RenameRequest, opts ...grpc.CallOption) (*RenameResponse, error)
	Statfs(ctx context.Context, in *StatfsRequest, opts ...grpc.CallOption) (*StatfsResponse, error)
	InitFs(ctx context.Context, in *InitFsRequest, opts ...grpc.CallOption) (*InitFsResponse, error)
	Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error)
}

type apiClient struct {
	cc *grpc.ClientConn
}

func NewApiClient(cc *grpc.ClientConn) ApiClient {
	return &apiClient{cc}
}

func (c *apiClient) Symlink(ctx context.Context, in *SymlinkRequest, opts ...grpc.CallOption) (*SymlinkResponse, error) {
	out := new(SymlinkResponse)
	err := grpc.Invoke(ctx, "/formicproto.Api/Symlink", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) Readlink(ctx context.Context, in *ReadlinkRequest, opts ...grpc.CallOption) (*ReadlinkResponse, error) {
	out := new(ReadlinkResponse)
	err := grpc.Invoke(ctx, "/formicproto.Api/Readlink", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) Getxattr(ctx context.Context, in *GetxattrRequest, opts ...grpc.CallOption) (*GetxattrResponse, error) {
	out := new(GetxattrResponse)
	err := grpc.Invoke(ctx, "/formicproto.Api/Getxattr", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) Setxattr(ctx context.Context, in *SetxattrRequest, opts ...grpc.CallOption) (*SetxattrResponse, error) {
	out := new(SetxattrResponse)
	err := grpc.Invoke(ctx, "/formicproto.Api/Setxattr", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) Listxattr(ctx context.Context, in *ListxattrRequest, opts ...grpc.CallOption) (*ListxattrResponse, error) {
	out := new(ListxattrResponse)
	err := grpc.Invoke(ctx, "/formicproto.Api/Listxattr", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) Removexattr(ctx context.Context, in *RemovexattrRequest, opts ...grpc.CallOption) (*RemovexattrResponse, error) {
	out := new(RemovexattrResponse)
	err := grpc.Invoke(ctx, "/formicproto.Api/Removexattr", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) Rename(ctx context.Context, in *RenameRequest, opts ...grpc.CallOption) (*RenameResponse, error) {
	out := new(RenameResponse)
	err := grpc.Invoke(ctx, "/formicproto.Api/Rename", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) Statfs(ctx context.Context, in *StatfsRequest, opts ...grpc.CallOption) (*StatfsResponse, error) {
	out := new(StatfsResponse)
	err := grpc.Invoke(ctx, "/formicproto.Api/Statfs", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) InitFs(ctx context.Context, in *InitFsRequest, opts ...grpc.CallOption) (*InitFsResponse, error) {
	out := new(InitFsResponse)
	err := grpc.Invoke(ctx, "/formicproto.Api/InitFs", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error) {
	out := new(CheckResponse)
	err := grpc.Invoke(ctx, "/formicproto.Api/Check", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Api service

type ApiServer interface {
	Symlink(context.Context, *SymlinkRequest) (*SymlinkResponse, error)
	Readlink(context.Context, *ReadlinkRequest) (*ReadlinkResponse, error)
	Getxattr(context.Context, *GetxattrRequest) (*GetxattrResponse, error)
	Setxattr(context.Context, *SetxattrRequest) (*SetxattrResponse, error)
	Listxattr(context.Context, *ListxattrRequest) (*ListxattrResponse, error)
	Removexattr(context.Context, *RemovexattrRequest) (*RemovexattrResponse, error)
	Rename(context.Context, *RenameRequest) (*RenameResponse, error)
	Statfs(context.Context, *StatfsRequest) (*StatfsResponse, error)
	InitFs(context.Context, *InitFsRequest) (*InitFsResponse, error)
	Check(context.Context, *CheckRequest) (*CheckResponse, error)
}

func RegisterApiServer(s *grpc.Server, srv ApiServer) {
	s.RegisterService(&_Api_serviceDesc, srv)
}

func _Api_Symlink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SymlinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).Symlink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/formicproto.Api/Symlink",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).Symlink(ctx, req.(*SymlinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_Readlink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadlinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).Readlink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/formicproto.Api/Readlink",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).Readlink(ctx, req.(*ReadlinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_Getxattr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetxattrRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).Getxattr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/formicproto.Api/Getxattr",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).Getxattr(ctx, req.(*GetxattrRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_Setxattr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetxattrRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).Setxattr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/formicproto.Api/Setxattr",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).Setxattr(ctx, req.(*SetxattrRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_Listxattr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListxattrRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).Listxattr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/formicproto.Api/Listxattr",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).Listxattr(ctx, req.(*ListxattrRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_Removexattr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemovexattrRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).Removexattr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/formicproto.Api/Removexattr",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).Removexattr(ctx, req.(*RemovexattrRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_Rename_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).Rename(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/formicproto.Api/Rename",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).Rename(ctx, req.(*RenameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_Statfs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatfsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).Statfs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/formicproto.Api/Statfs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).Statfs(ctx, req.(*StatfsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_InitFs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitFsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).InitFs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/formicproto.Api/InitFs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).InitFs(ctx, req.(*InitFsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/formicproto.Api/Check",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).Check(ctx, req.(*CheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Api_serviceDesc = grpc.ServiceDesc{
	ServiceName: "formicproto.Api",
	HandlerType: (*ApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Symlink",
			Handler:    _Api_Symlink_Handler,
		},
		{
			MethodName: "Readlink",
			Handler:    _Api_Readlink_Handler,
		},
		{
			MethodName: "Getxattr",
			Handler:    _Api_Getxattr_Handler,
		},
		{
			MethodName: "Setxattr",
			Handler:    _Api_Setxattr_Handler,
		},
		{
			MethodName: "Listxattr",
			Handler:    _Api_Listxattr_Handler,
		},
		{
			MethodName: "Removexattr",
			Handler:    _Api_Removexattr_Handler,
		},
		{
			MethodName: "Rename",
			Handler:    _Api_Rename_Handler,
		},
		{
			MethodName: "Statfs",
			Handler:    _Api_Statfs_Handler,
		},
		{
			MethodName: "InitFs",
			Handler:    _Api_InitFs_Handler,
		},
		{
			MethodName: "Check",
			Handler:    _Api_Check_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "formic_api.proto",
}

// Client API for FileSystemAPI service

type FileSystemAPIClient interface {
	CreateFS(ctx context.Context, in *CreateFSRequest, opts ...grpc.CallOption) (*CreateFSResponse, error)
	ListFS(ctx context.Context, in *ListFSRequest, opts ...grpc.CallOption) (*ListFSResponse, error)
	ShowFS(ctx context.Context, in *ShowFSRequest, opts ...grpc.CallOption) (*ShowFSResponse, error)
	DeleteFS(ctx context.Context, in *DeleteFSRequest, opts ...grpc.CallOption) (*DeleteFSResponse, error)
	UpdateFS(ctx context.Context, in *UpdateFSRequest, opts ...grpc.CallOption) (*UpdateFSResponse, error)
	GrantAddrFS(ctx context.Context, in *GrantAddrFSRequest, opts ...grpc.CallOption) (*GrantAddrFSResponse, error)
	RevokeAddrFS(ctx context.Context, in *RevokeAddrFSRequest, opts ...grpc.CallOption) (*RevokeAddrFSResponse, error)
}

type fileSystemAPIClient struct {
	cc *grpc.ClientConn
}

func NewFileSystemAPIClient(cc *grpc.ClientConn) FileSystemAPIClient {
	return &fileSystemAPIClient{cc}
}

func (c *fileSystemAPIClient) CreateFS(ctx context.Context, in *CreateFSRequest, opts ...grpc.CallOption) (*CreateFSResponse, error) {
	out := new(CreateFSResponse)
	err := grpc.Invoke(ctx, "/formicproto.FileSystemAPI/CreateFS", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileSystemAPIClient) ListFS(ctx context.Context, in *ListFSRequest, opts ...grpc.CallOption) (*ListFSResponse, error) {
	out := new(ListFSResponse)
	err := grpc.Invoke(ctx, "/formicproto.FileSystemAPI/ListFS", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileSystemAPIClient) ShowFS(ctx context.Context, in *ShowFSRequest, opts ...grpc.CallOption) (*ShowFSResponse, error) {
	out := new(ShowFSResponse)
	err := grpc.Invoke(ctx, "/formicproto.FileSystemAPI/ShowFS", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileSystemAPIClient) DeleteFS(ctx context.Context, in *DeleteFSRequest, opts ...grpc.CallOption) (*DeleteFSResponse, error) {
	out := new(DeleteFSResponse)
	err := grpc.Invoke(ctx, "/formicproto.FileSystemAPI/DeleteFS", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileSystemAPIClient) UpdateFS(ctx context.Context, in *UpdateFSRequest, opts ...grpc.CallOption) (*UpdateFSResponse, error) {
	out := new(UpdateFSResponse)
	err := grpc.Invoke(ctx, "/formicproto.FileSystemAPI/UpdateFS", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileSystemAPIClient) GrantAddrFS(ctx context.Context, in *GrantAddrFSRequest, opts ...grpc.CallOption) (*GrantAddrFSResponse, error) {
	out := new(GrantAddrFSResponse)
	err := grpc.Invoke(ctx, "/formicproto.FileSystemAPI/GrantAddrFS", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileSystemAPIClient) RevokeAddrFS(ctx context.Context, in *RevokeAddrFSRequest, opts ...grpc.CallOption) (*RevokeAddrFSResponse, error) {
	out := new(RevokeAddrFSResponse)
	err := grpc.Invoke(ctx, "/formicproto.FileSystemAPI/RevokeAddrFS", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FileSystemAPI service

type FileSystemAPIServer interface {
	CreateFS(context.Context, *CreateFSRequest) (*CreateFSResponse, error)
	ListFS(context.Context, *ListFSRequest) (*ListFSResponse, error)
	ShowFS(context.Context, *ShowFSRequest) (*ShowFSResponse, error)
	DeleteFS(context.Context, *DeleteFSRequest) (*DeleteFSResponse, error)
	UpdateFS(context.Context, *UpdateFSRequest) (*UpdateFSResponse, error)
	GrantAddrFS(context.Context, *GrantAddrFSRequest) (*GrantAddrFSResponse, error)
	RevokeAddrFS(context.Context, *RevokeAddrFSRequest) (*RevokeAddrFSResponse, error)
}

func RegisterFileSystemAPIServer(s *grpc.Server, srv FileSystemAPIServer) {
	s.RegisterService(&_FileSystemAPI_serviceDesc, srv)
}

func _FileSystemAPI_CreateFS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileSystemAPIServer).CreateFS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/formicproto.FileSystemAPI/CreateFS",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileSystemAPIServer).CreateFS(ctx, req.(*CreateFSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileSystemAPI_ListFS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileSystemAPIServer).ListFS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/formicproto.FileSystemAPI/ListFS",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileSystemAPIServer).ListFS(ctx, req.(*ListFSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileSystemAPI_ShowFS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShowFSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileSystemAPIServer).ShowFS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/formicproto.FileSystemAPI/ShowFS",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileSystemAPIServer).ShowFS(ctx, req.(*ShowFSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileSystemAPI_DeleteFS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileSystemAPIServer).DeleteFS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/formicproto.FileSystemAPI/DeleteFS",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileSystemAPIServer).DeleteFS(ctx, req.(*DeleteFSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileSystemAPI_UpdateFS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileSystemAPIServer).UpdateFS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/formicproto.FileSystemAPI/UpdateFS",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileSystemAPIServer).UpdateFS(ctx, req.(*UpdateFSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileSystemAPI_GrantAddrFS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrantAddrFSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileSystemAPIServer).GrantAddrFS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/formicproto.FileSystemAPI/GrantAddrFS",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileSystemAPIServer).GrantAddrFS(ctx, req.(*GrantAddrFSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileSystemAPI_RevokeAddrFS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeAddrFSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileSystemAPIServer).RevokeAddrFS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/formicproto.FileSystemAPI/RevokeAddrFS",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileSystemAPIServer).RevokeAddrFS(ctx, req.(*RevokeAddrFSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FileSystemAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "formicproto.FileSystemAPI",
	HandlerType: (*FileSystemAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFS",
			Handler:    _FileSystemAPI_CreateFS_Handler,
		},
		{
			MethodName: "ListFS",
			Handler:    _FileSystemAPI_ListFS_Handler,
		},
		{
			MethodName: "ShowFS",
			Handler:    _FileSystemAPI_ShowFS_Handler,
		},
		{
			MethodName: "DeleteFS",
			Handler:    _FileSystemAPI_DeleteFS_Handler,
		},
		{
			MethodName: "UpdateFS",
			Handler:    _FileSystemAPI_UpdateFS_Handler,
		},
		{
			MethodName: "GrantAddrFS",
			Handler:    _FileSystemAPI_GrantAddrFS_Handler,
		},
		{
			MethodName: "RevokeAddrFS",
			Handler:    _FileSystemAPI_RevokeAddrFS_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "formic_api.proto",
}

func init() { proto.RegisterFile("formic_api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1386 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x57, 0xcd, 0x6e, 0xdb, 0xc6,
	0x13, 0x0f, 0x25, 0xca, 0x96, 0xc6, 0x96, 0xa5, 0x6c, 0xf2, 0x0f, 0xf4, 0x57, 0xd2, 0xd6, 0x25,
	0x9a, 0xd4, 0x49, 0x0b, 0x1f, 0x9c, 0x1e, 0xdc, 0x16, 0x68, 0xeb, 0xda, 0x55, 0x60, 0x20, 0x0d,
	0x02, 0x32, 0x01, 0x72, 0x2b, 0x68, 0x73, 0xed, 0x2c, 0x24, 0x91, 0x0a, 0xb9, 0xb2, 0xa3, 0x5e,
	0x7a, 0xe8, 0x1b, 0xf4, 0xde, 0x63, 0x5f, 0xa6, 0x4f, 0xd0, 0x6b, 0xdf, 0xa4, 0x98, 0xd9, 0x5d,
	0x7e, 0xac, 0x65, 0x3a, 0x31, 0x8a, 0xde, 0x66, 0x66, 0x87, 0xbf, 0xf9, 0xd8, 0xd9, 0x99, 0x21,
	0xf4, 0x4f, 0x92, 0x74, 0x2a, 0x8e, 0x7f, 0x0a, 0x67, 0x62, 0x7b, 0x96, 0x26, 0x32, 0x61, 0x6b,
	0x4a, 0x42, 0x8c, 0xf7, 0x97, 0x03, 0xee, 0x9e, 0x94, 0x29, 0xbb, 0x0d, 0x2d, 0x11, 0x27, 0x11,
	0x1f, 0x38, 0x9b, 0xce, 0x96, 0xeb, 0x2b, 0x06, 0xa5, 0xa1, 0x14, 0x53, 0x3e, 0x68, 0x6c, 0x3a,
	0x5b, 0x4d, 0x5f, 0x31, 0x28, 0x9d, 0x92, 0xb4, 0xa9, 0xa4, 0x53, 0x23, 0x3d, 0x26, 0xa9, 0xab,
	0xa4, 0xc4, 0xb0, 0x3b, 0xb0, 0x72, 0x9c, 0x92, 0xb8, 0x45, 0x62, 0xcd, 0x31, 0x06, 0xee, 0x14,
	0xcd, 0xad, 0x6c, 0x3a, 0x5b, 0x5d, 0x9f, 0x68, 0x44, 0x38, 0x0b, 0x27, 0x22, 0x1a, 0xac, 0x6e,
	0x3a, 0x5b, 0x2d, 0x5f, 0x31, 0xa8, 0x99, 0x89, 0x9f, 0xf9, 0xa0, 0x4d, 0x8e, 0x11, 0xcd, 0xfa,
	0xd0, 0x9c, 0x8b, 0x68, 0xd0, 0xa1, 0x8f, 0x91, 0x44, 0xc9, 0xa9, 0x88, 0x06, 0xa0, 0x24, 0xa7,
	0x22, 0xf2, 0xde, 0xc2, 0x46, 0xb0, 0x98, 0x4e, 0x44, 0x3c, 0xf6, 0xf9, 0x9b, 0x39, 0xcf, 0x24,
	0xfa, 0x32, 0x0b, 0x53, 0x1e, 0x4b, 0x1d, 0xa4, 0xe6, 0xd0, 0x42, 0x1c, 0xea, 0x20, 0x3b, 0x3e,
	0xd1, 0xa8, 0x2b, 0xc3, 0xf4, 0x94, 0x4b, 0x0a, 0xb2, 0xe3, 0x6b, 0xce, 0x58, 0x76, 0x2f, 0x58,
	0x6e, 0x15, 0x96, 0x23, 0xe8, 0xe5, 0x96, 0xb3, 0x59, 0x12, 0x67, 0xfc, 0xbd, 0x4c, 0xdf, 0x07,
	0x37, 0x94, 0x32, 0x25, 0xc3, 0x6b, 0x3b, 0x37, 0xb7, 0x4b, 0xf7, 0xb5, 0x8d, 0x77, 0xe5, 0xd3,
	0xb1, 0xf7, 0x29, 0xf4, 0x7c, 0x1e, 0x46, 0xe5, 0x00, 0x97, 0x5e, 0xa2, 0xf7, 0x08, 0xfa, 0x85,
	0x62, 0xe1, 0x8f, 0x0e, 0xcf, 0x29, 0x87, 0xe7, 0x8d, 0xa1, 0xf7, 0x84, 0xcb, 0xb7, 0x68, 0xa0,
	0x16, 0x74, 0xa9, 0xe3, 0xe6, 0xa6, 0x9a, 0xea, 0x4e, 0xe9, 0xa6, 0x86, 0xd0, 0x9e, 0x25, 0x99,
	0x90, 0x22, 0x89, 0x75, 0xd2, 0x72, 0xde, 0xdb, 0x82, 0x7e, 0x61, 0x4c, 0x3b, 0x76, 0x1b, 0x5a,
	0x24, 0x20, 0x6b, 0xeb, 0xbe, 0x62, 0xbc, 0x5f, 0x1d, 0xe8, 0x05, 0xd7, 0xf6, 0x4b, 0xd5, 0xd5,
	0x5c, 0x39, 0xb6, 0xee, 0x2b, 0xa6, 0xce, 0x33, 0xfc, 0xe2, 0x64, 0x12, 0x9e, 0x66, 0xfa, 0x56,
	0x15, 0xe3, 0x31, 0xe8, 0x07, 0x96, 0xbf, 0xde, 0x2b, 0xe8, 0x3f, 0x15, 0xd9, 0x3b, 0x7a, 0x46,
	0xd9, 0x69, 0x5c, 0x92, 0x9d, 0xa6, 0x95, 0x9d, 0x87, 0x70, 0xb3, 0x84, 0x5c, 0x9b, 0x9e, 0x6f,
	0x80, 0xf9, 0x7c, 0x9a, 0x9c, 0xf1, 0xeb, 0x25, 0xc8, 0xfb, 0x1f, 0xdc, 0xaa, 0x7c, 0xaf, 0x63,
	0xfb, 0x05, 0xba, 0x3e, 0x47, 0x05, 0x83, 0x78, 0x0f, 0x3a, 0xc9, 0x24, 0x7a, 0x5e, 0x2e, 0xe4,
	0x42, 0x80, 0xa7, 0x31, 0x3f, 0xd7, 0xa7, 0x0d, 0x75, 0x9a, 0x0b, 0xd8, 0x00, 0x56, 0x93, 0x49,
	0xf4, 0x2c, 0xd4, 0x6d, 0xa3, 0xe3, 0x1b, 0x16, 0x4f, 0x62, 0x7e, 0x4e, 0x27, 0xae, 0x3a, 0xd1,
	0xac, 0xd7, 0x87, 0x0d, 0xe3, 0x80, 0x76, 0xa9, 0x07, 0xdd, 0x40, 0x86, 0xf2, 0x24, 0xd3, 0x2e,
	0x79, 0x7f, 0x3a, 0xb0, 0x61, 0x24, 0x45, 0x6d, 0x1f, 0x4d, 0x92, 0xe3, 0x71, 0x66, 0xde, 0x9a,
	0xe2, 0x30, 0x1f, 0x47, 0x27, 0x29, 0xe7, 0xda, 0x37, 0xc5, 0x90, 0x76, 0x78, 0x16, 0x8a, 0x09,
	0xb9, 0x85, 0xda, 0xc4, 0x51, 0x09, 0x88, 0x09, 0xcf, 0xc8, 0x27, 0xd7, 0x57, 0x0c, 0x49, 0x09,
	0xa3, 0xa5, 0xa5, 0x84, 0x81, 0xc8, 0x74, 0xb7, 0xaa, 0x9b, 0x29, 0x86, 0xe2, 0x0a, 0xa7, 0x7c,
	0xc2, 0x63, 0x6a, 0x68, 0x5d, 0xdf, 0xb0, 0x68, 0xf3, 0x24, 0xcd, 0x9b, 0x5a, 0xd7, 0xd7, 0x1c,
	0x46, 0x77, 0x18, 0x0b, 0x39, 0xca, 0xa3, 0xeb, 0xc3, 0x86, 0x11, 0xe8, 0x04, 0xec, 0xc2, 0xfa,
	0xfe, 0x6b, 0x7e, 0x3c, 0x7e, 0xff, 0x4b, 0xfe, 0x0c, 0xba, 0xfa, 0x4b, 0x9d, 0xa7, 0x21, 0xb4,
	0x53, 0x4d, 0xeb, 0x2e, 0x90, 0xf3, 0xde, 0xef, 0x4d, 0x80, 0x43, 0x84, 0xfa, 0x21, 0x96, 0xe9,
	0x02, 0x43, 0x39, 0xe3, 0x69, 0x86, 0x65, 0xea, 0xa8, 0x50, 0x34, 0x4b, 0xf6, 0xb3, 0x03, 0x91,
	0x92, 0xa9, 0xb6, 0xaf, 0x98, 0x77, 0x6c, 0x61, 0xa5, 0xae, 0xe8, 0x56, 0xba, 0x62, 0x1e, 0x54,
	0xab, 0x1c, 0x14, 0xd6, 0x57, 0x12, 0xf1, 0xfd, 0x64, 0x1e, 0x4b, 0xca, 0x34, 0xd6, 0x97, 0x11,
	0x20, 0x96, 0xc8, 0x9e, 0x8a, 0x78, 0x4c, 0xc9, 0x6e, 0xfb, 0x9a, 0x2b, 0x75, 0xba, 0x76, 0xa5,
	0x91, 0xef, 0x9a, 0x97, 0xd4, 0xd9, 0x6c, 0x6e, 0xad, 0xed, 0x78, 0x15, 0x1f, 0x8b, 0xd0, 0xb7,
	0x5f, 0xa1, 0x12, 0x91, 0xfa, 0xb5, 0x95, 0xea, 0x0b, 0x2a, 0xf5, 0x75, 0x0f, 0x3a, 0x44, 0x05,
	0x78, 0xb1, 0x6b, 0xca, 0xbf, 0x5c, 0x80, 0x57, 0x72, 0x92, 0x1d, 0x46, 0x83, 0x2e, 0x3d, 0x5c,
	0xa2, 0x87, 0xbb, 0x00, 0x05, 0x3c, 0x0e, 0x92, 0x31, 0x5f, 0xe8, 0xab, 0x40, 0xb2, 0x68, 0x5c,
	0x8d, 0x52, 0xe3, 0xfa, 0xaa, 0xb1, 0xeb, 0x78, 0x0b, 0xe8, 0xbc, 0x48, 0xa6, 0x47, 0x99, 0x4c,
	0x62, 0x2a, 0xbf, 0x88, 0x46, 0xac, 0xa3, 0x26, 0x6f, 0x64, 0xe6, 0xf1, 0x9b, 0xf2, 0xec, 0x7e,
	0x63, 0xe6, 0x2e, 0xb9, 0xd1, 0x2c, 0xdc, 0x28, 0xd2, 0xed, 0x96, 0xd3, 0x5d, 0x84, 0xd9, 0x2a,
	0x87, 0xe9, 0xcd, 0xa1, 0x75, 0x20, 0x52, 0xb9, 0xf8, 0x8f, 0xcd, 0xbe, 0x84, 0xce, 0x48, 0x4c,
	0xf8, 0xf7, 0xc8, 0xd5, 0xd4, 0x23, 0x03, 0x37, 0x0a, 0x65, 0xa8, 0x33, 0x46, 0x34, 0x16, 0xfa,
	0x31, 0x56, 0x7e, 0x36, 0x9f, 0x9a, 0x2e, 0x6b, 0x78, 0xef, 0x31, 0xb4, 0x7e, 0x4c, 0xa2, 0x51,
	0x80, 0x1f, 0x52, 0x0b, 0x52, 0xe9, 0x27, 0x1a, 0x7d, 0xc1, 0xde, 0x32, 0xcf, 0xf4, 0x43, 0xd2,
	0x9c, 0xf7, 0x2d, 0xf4, 0xf6, 0x53, 0x1e, 0x4a, 0x3e, 0x0a, 0x4a, 0xef, 0xf0, 0x45, 0x32, 0xe6,
	0xb1, 0xfe, 0x5e, 0x31, 0x08, 0x30, 0x0a, 0x9e, 0x15, 0x2f, 0x51, 0x73, 0xde, 0x03, 0xe8, 0x17,
	0x00, 0xfa, 0x39, 0x32, 0x70, 0x0f, 0xd0, 0x73, 0xed, 0x00, 0xd2, 0xde, 0x7d, 0xe8, 0xe2, 0x0c,
	0xb8, 0xc2, 0x8c, 0xf7, 0x09, 0x6c, 0x18, 0xb5, 0x1a, 0xb0, 0x2f, 0xa1, 0x1b, 0xbc, 0x4e, 0xce,
	0xaf, 0xf2, 0x99, 0x81, 0x3b, 0x0a, 0x44, 0x64, 0x7a, 0x07, 0xd2, 0x68, 0xc0, 0x7c, 0x5a, 0x63,
	0xe0, 0x6b, 0xe8, 0x1d, 0xf0, 0x09, 0xbf, 0x3a, 0x2d, 0xcb, 0x4c, 0x3c, 0x80, 0x7e, 0xf1, 0x71,
	0x8d, 0x11, 0x01, 0xbd, 0x97, 0xb3, 0x28, 0xbc, 0x96, 0x11, 0xf6, 0x39, 0xac, 0x62, 0x11, 0x65,
	0x8b, 0x4c, 0xb7, 0x26, 0x56, 0x79, 0xf6, 0x54, 0x09, 0xbe, 0x51, 0x41, 0x97, 0x0a, 0x53, 0x35,
	0x2e, 0xf9, 0xc0, 0x9e, 0xa4, 0x61, 0x2c, 0xf7, 0xa2, 0x28, 0xbd, 0x8e, 0x57, 0x0c, 0x5c, 0xfc,
	0x54, 0xcf, 0x45, 0xa2, 0xbd, 0x87, 0x70, 0xab, 0x82, 0x59, 0x63, 0x3e, 0xc0, 0xe9, 0x7d, 0x96,
	0x8c, 0xf9, 0xbf, 0x69, 0xff, 0x11, 0xdc, 0xae, 0x82, 0xd6, 0x38, 0xf0, 0x9b, 0x03, 0xed, 0x03,
	0x91, 0x5e, 0x35, 0x2a, 0x96, 0xad, 0x66, 0x1b, 0xd0, 0x10, 0xa6, 0x2b, 0x34, 0x44, 0xc4, 0xbe,
	0x80, 0x8e, 0x34, 0x7d, 0x8d, 0xfa, 0xc2, 0xda, 0xce, 0x9d, 0xca, 0x15, 0xe5, 0x5d, 0xcf, 0x2f,
	0x14, 0x11, 0x59, 0x2e, 0x66, 0x5c, 0x6f, 0x6b, 0x44, 0xef, 0xfc, 0xdd, 0x82, 0xe6, 0xde, 0x4c,
	0xb0, 0x11, 0xac, 0xea, 0x65, 0x9c, 0xdd, 0xad, 0x20, 0x55, 0x7f, 0x0e, 0x86, 0xf7, 0x96, 0x1f,
	0xea, 0x79, 0x78, 0x83, 0x1d, 0x42, 0xdb, 0x6c, 0xd1, 0xac, 0xaa, 0x6b, 0x6d, 0xe1, 0xc3, 0x0f,
	0x2e, 0x39, 0x2d, 0x43, 0x99, 0xbd, 0xd7, 0x82, 0xb2, 0x76, 0x6f, 0x0b, 0xca, 0x5e, 0x96, 0x15,
	0x54, 0xb0, 0x1c, 0x2a, 0xa8, 0x85, 0x0a, 0x2e, 0x42, 0x3d, 0x85, 0x4e, 0xbe, 0x6f, 0xb2, 0xaa,
	0xb6, 0xbd, 0xe1, 0x0e, 0x3f, 0xbc, 0xec, 0x38, 0x47, 0xf3, 0x61, 0xad, 0xb4, 0x52, 0xb2, 0x8f,
	0xac, 0x9c, 0xd8, 0xcb, 0xea, 0x70, 0xf3, 0x72, 0x85, 0x1c, 0x73, 0x1f, 0x56, 0xd4, 0x3a, 0xc8,
	0x86, 0x96, 0x76, 0x69, 0x49, 0x1d, 0xde, 0x5d, 0x7a, 0x56, 0x06, 0x51, 0xfb, 0xa2, 0x05, 0x52,
	0x59, 0x2b, 0x2d, 0x90, 0xea, 0x82, 0xa9, 0x40, 0xd4, 0x5e, 0x66, 0x81, 0x54, 0xb6, 0x37, 0x0b,
	0xc4, 0x5a, 0xe4, 0x6e, 0xb0, 0xef, 0xa0, 0x45, 0x0b, 0x19, 0xfb, 0x7f, 0x45, 0xaf, 0xbc, 0xde,
	0x0d, 0x87, 0xcb, 0x8e, 0x0c, 0xc2, 0xce, 0x1f, 0x2e, 0x74, 0xb1, 0x59, 0x05, 0x8b, 0x4c, 0xf2,
	0xe9, 0xde, 0xf3, 0x43, 0xac, 0x07, 0x33, 0x58, 0xac, 0x7a, 0xb0, 0x06, 0x96, 0x55, 0x0f, 0xf6,
	0x34, 0x52, 0x31, 0xaa, 0xa1, 0x62, 0xc5, 0x58, 0x19, 0x48, 0x56, 0x8c, 0xd5, 0x29, 0xa4, 0xb3,
	0x4d, 0x83, 0xc3, 0xce, 0x76, 0x79, 0x10, 0xd9, 0xd9, 0xae, 0x4c, 0x1a, 0x55, 0xe4, 0x66, 0x34,
	0x58, 0x41, 0x59, 0xe3, 0xc6, 0x0a, 0xca, 0x9e, 0x27, 0x0a, 0xca, 0xb4, 0x74, 0x0b, 0xca, 0x1a,
	0x2a, 0x16, 0x94, 0x3d, 0x07, 0x54, 0x85, 0x97, 0x3a, 0xb4, 0x55, 0xe1, 0x17, 0xe7, 0x81, 0x55,
	0xe1, 0x4b, 0x9a, 0xbb, 0x77, 0x83, 0xbd, 0x84, 0xf5, 0x72, 0xd7, 0x65, 0xf6, 0xab, 0xb8, 0xd0,
	0xe5, 0x87, 0x1f, 0xd7, 0x68, 0x18, 0xd8, 0xa3, 0x15, 0x3a, 0x7d, 0xfc, 0x4f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xe9, 0xfd, 0xc5, 0x73, 0x0d, 0x12, 0x00, 0x00,
}
